### ISSUE TITLE
The dynamic operation request to API 'saperppreview' operation 'GenerateJsonSchema' failed with status code 'BadRequest'. This may indicate invalid input parameters. Error response: {\r\n \"error\": {\r\n \"code\": \"InvalidSapSystem\",\r\n \"message\": \"Los datos JSON del sistema SAP tienen un formato incorrecto y no se analizaron.\",\r\n \"target\": \"sapSystemHeader\"\r\n }\r\n}\"."}}".

### ISSUE THREAD

**Issue by raulcocerasanchez** [jongilman88/PowerPlatformSAPIntegration#3]
DOES NOT CORRECTLY SOLVE THE VARIABLE . HOW COULD I SOLVE IT? FLOWS GIVE ERROR IN THE SAP CONNECTION

Edit SAP Development variable  : {"AppServerHost":128.X.XX.XX,"Client":"100","SystemNumber":"00","LogonType":"ApplicationServer"}

**Comment by EllenWehrle** [comment]
Hello, the first thing we would like for you to consider is that this is a firewall issue and that the data gateway may need to be reconfigured. You will also need to ensure that you are utilizing the latest version of [Microsoft's on-premises data gateway](https://www.microsoft.com/en-us/download/details.aspx?id=53127). Please keep us posted on your progress.

**Comment by jongilman88** [comment]
Try importing the new solution that was just uploaded today.
