### ISSUE TITLE
\deploySAPSolution.ps1  script execution error 

### ISSUE THREAD

**Issue by cjpark-sapcsa** [jongilman88/PowerPlatformSAPIntegration#7]
Hi Team, 

Does anyone made success of the \deploySAPSolution.ps1  script execution  ? 

PS C:\PP_SAP_solutions\deployment> .\deploySAPSolution.ps1 -url https://XXXXXXXXXX.crm5.dynamics.com/ -solutionPath C:\PP_SAP_solutions\deployment\SAPIntegrationPublicPreview_unmanaged.zip -schemaPath C:\PP_SAP_solutions\deployment\schema.xml -configDataPath C:\PP_SAP_solutions\deployment\configdata.zip

C:\PP_SAP_solutions\deployment\deploySAPSolution.ps1 : A parameter cannot be found that matches parameter name 'schemaPath'.
At line:1 char:168
+ ... loyment\SAPIntegrationPublicPreview_unmanaged.zip -schemaPath C:\PP_S ...
+                                                       ~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [deploySAPSolution.ps1], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,deploySAPSolution.ps1

Best Regards

ChanJin

**Comment by jongilman88** [comment]
This has been resolved by: https://github.com/jongilman88/PowerPlatformSAPIntegration/pull/6
